#!/bin/csh -f
# =============================================================================
# Auto-generated by Spark StdCell Automation Framework
# Stage       : release
# Description : 发布与归档
# Project     : fake_stdcell_28nm
# Tech Node   : 28nm
# =============================================================================
# DO NOT EDIT MANUALLY — changes will be overwritten by spark framework.
# =============================================================================

# ---------- 环境校验 -----------------------------------------------------------
if ( ! $?SPARK_HOME ) then
    echo "[ERROR] SPARK_HOME is not set. Please source spark.csh first."
    exit 1
endif

# ---------- 运行目录切换 -------------------------------------------------------
set RUN_DIR = "."
if ( ! -d $RUN_DIR ) mkdir -p $RUN_DIR
cd $RUN_DIR

# ---------- 日志目录 -----------------------------------------------------------
set LOG_DIR = "./log"
if ( ! -d $LOG_DIR ) mkdir -p $LOG_DIR
set LOG_FILE = "$LOG_DIR/release.log"

echo "[INFO]  Stage     : release" | tee -a $LOG_FILE
echo "[INFO]  Start time: `date '+%Y-%m-%d %H:%M:%S'`" | tee -a $LOG_FILE
echo "[INFO]  Run dir   : $RUN_DIR" | tee -a $LOG_FILE

# ---------- 工具路径 -----------------------------------------------------------

# ---------- PVT Corners（若适用）----------------------------------------------

# ---------- 输入/输出路径（若适用）-------------------------------------------

# ---------- 主体执行 -----------------------------------------------------------
echo "[INFO]  Executing 发布与归档..." | tee -a $LOG_FILE

# 此阶段无外部工具调用（由 Python 内部处理）
set EXIT_CODE = 0

# ---------- 结果检查 -----------------------------------------------------------
echo "[INFO]  End time  : `date '+%Y-%m-%d %H:%M:%S'`" | tee -a $LOG_FILE
if ( $EXIT_CODE != 0 ) then
    echo "[ERROR] release failed with exit code: $EXIT_CODE" | tee -a $LOG_FILE
    exit $EXIT_CODE
else
    echo "[INFO]  release completed successfully." | tee -a $LOG_FILE
endif

exit 0
