#!/bin/csh -f
# =============================================================================
# Auto-generated by Spark StdCell Automation Framework
# Stage       : gen_gds
# Description : GDS 版图生成
# Project     : fake_stdcell_28nm
# Tech Node   : 28nm
# =============================================================================
# DO NOT EDIT MANUALLY — changes will be overwritten by spark framework.
# =============================================================================

# ---------- 环境校验 -----------------------------------------------------------
if ( ! $?SPARK_HOME ) then
    echo "[ERROR] SPARK_HOME is not set. Please source spark.csh first."
    exit 1
endif

# ---------- 运行目录切换 -------------------------------------------------------
set RUN_DIR = "C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\work\fake_stdcell\v1.0\gen_gds\run"
if ( ! -d $RUN_DIR ) mkdir -p $RUN_DIR
cd $RUN_DIR

# ---------- 日志目录 -----------------------------------------------------------
set LOG_DIR = "C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\work\fake_stdcell\v1.0\gen_gds\run\log"
if ( ! -d $LOG_DIR ) mkdir -p $LOG_DIR
set LOG_FILE = "$LOG_DIR/gen_gds.log"

echo "[INFO]  Stage     : gen_gds" | tee -a $LOG_FILE
echo "[INFO]  Start time: `date '+%Y-%m-%d %H:%M:%S'`" | tee -a $LOG_FILE
echo "[INFO]  Run dir   : $RUN_DIR" | tee -a $LOG_FILE

# ---------- 工具路径 -----------------------------------------------------------
set TOOL_CMD = "echo -no_gui -batch -execute C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\work\fake_stdcell\v1.0\gen_gds\scr\gen_gds.tcl"
if ( ! -x `which $TOOL_CMD:t` ) then
    # 尝试直接以完整路径检查
    if ( ! -f "$TOOL_CMD" ) then
        echo "[WARN]  Tool not found: $TOOL_CMD" | tee -a $LOG_FILE
    endif
endif

# ---------- PVT Corners（若适用）----------------------------------------------
set CORNERS = ( \
    ff_0p99v_m40c \
    tt_1p10v_025c \
    ss_1p21v_125c
)
echo "[INFO]  Corners   : $CORNERS" | tee -a $LOG_FILE

# ---------- 输入/输出路径（若适用）-------------------------------------------
set GDS_SOURCE    = "C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\input\fake_stdcell.gds"
set OUTPUT_GDS    = "C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\work\fake_stdcell\v1.0\gen_gds\release\output_file\stdcell_merge.gds"

# ---------- 主体执行 -----------------------------------------------------------
echo "[INFO]  Executing GDS 版图生成..." | tee -a $LOG_FILE

echo -no_gui -batch -execute C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\work\fake_stdcell\v1.0\gen_gds\scr\gen_gds.tcl \
    >>& $LOG_FILE

set EXIT_CODE = $status

# ---------- 结果检查 -----------------------------------------------------------
echo "[INFO]  End time  : `date '+%Y-%m-%d %H:%M:%S'`" | tee -a $LOG_FILE
if ( $EXIT_CODE != 0 ) then
    echo "[ERROR] gen_gds failed with exit code: $EXIT_CODE" | tee -a $LOG_FILE
    exit $EXIT_CODE
else
    echo "[INFO]  gen_gds completed successfully." | tee -a $LOG_FILE
endif

exit 0
