##############################################################################
# Auto-generated by Spark StdCell Automation Framework
# Stage     : gen_gds
# Project   : fake_stdcell_28nm
# Tech Node : 28nm
# DO NOT EDIT MANUALLY
##############################################################################

# ---------- 全局变量 ----------------------------------------------------------
set DESIGN_NAME   "fake_stdcell_28nm"
set TECH_NODE     "28nm"
set RUN_DIR       "C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\work\gen_gds\run"
set LOG_DIR       "C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\work\gen_gds\run\log"

set GDS_SOURCE    "C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\input\fake_stdcell.gds"
set OUTPUT_GDS    "C:\Users\Asneiitor\Desktop\AI_exploree\Altas\test_work\work\gen_gds\release\output_file\stdcell_merge.gds"

# ---------- 消息日志 ----------------------------------------------------------
proc spark_log { level msg } {
    set ts [clock format [clock seconds] -format "%Y-%m-%d %H:%M:%S"]
    puts "\[$ts\] \[$level\] $msg"
}

spark_log INFO "=== Spark Innovus Script Started ==="
spark_log INFO "Design : $DESIGN_NAME"
spark_log INFO "Tech   : $TECH_NODE"

# ---------- 读取技术文件（LEF）------------------------------------------------

# ---------- 读取 GDS -----------------------------------------------------------
spark_log INFO "Reading GDS: $GDS_SOURCE"
read_gds -lib $GDS_SOURCE -view layout

# ---------- PVT Corner 设置 ---------------------------------------------------
# Corner: ff_0p99v_m40c
spark_log INFO "Configuring corner: ff_0p99v_m40c"
# Corner: tt_1p10v_025c
spark_log INFO "Configuring corner: tt_1p10v_025c"
# Corner: ss_1p21v_125c
spark_log INFO "Configuring corner: ss_1p21v_125c"

# ---------- GDS 导出（gen_gds 阶段专用）--------------------------------------
spark_log INFO "Exporting merged GDS to: $OUTPUT_GDS"
set dbgdsout_options {
    -hierarchical
    -merge_file $OUTPUT_GDS
}
stream_out $OUTPUT_GDS \
    -lib_name $DESIGN_NAME \
    -view layout \
    -map_file ${SPARK_TMPL}/gds_layer.map

spark_log INFO "GDS export completed: $OUTPUT_GDS"

# ---------- 收尾 --------------------------------------------------------------
spark_log INFO "=== Spark Innovus Script Finished ==="
exit 0
